name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-analyze:
    name: Build and Analyze
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Build Environment
        uses: ./.github/actions/setup-build-env
        with:
          os: 'Linux'
          build_type: 'Release'
        
      - name: Generate Compilation Database
        run: |
          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - name: Downgrade C++ Standard for SonarCloud
        run: |
          sed -i 's/-std=c++26/-std=c++23/g' build/compile_commands.json
          sed -i 's/-std=gnu++26/-std=gnu++23/g' build/compile_commands.json
          sed -i 's/-std=c++2c/-std=c++2b/g' build/compile_commands.json
          sed -i 's/-std=gnu++2c/-std=gnu++2b/g' build/compile_commands.json

      - name: SonarQube/SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
